version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Only if you need access from host (optional)
    command: --default-authentication-plugin=caching_sha2_password
  ###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
